baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SZK | Suzuka Ka'
theme = 'gallery'
[markup.goldmark.renderer]
unsafe= true
[params]
  keywords = ['gamedev', 'gamedeveloper', 'engeneer', 'multimedia engineer', '2D art', '3D art', 'music production', 'alicante', 'spain']
  socials = ['github', 'twitter', 'youtube','gumroad', 'itchio', 'email']