baseURL = 'https://example.org/'
copyright = "Suzuka Ka"
# languageCode = 'en-us'
# languageCode = 'es-es'
title = 'SZK | Suzuka Ka'
theme = 'gallery'

# Multilingual
# INFO https://gohugo.io/content-management/multilingual/
defaultContentLanguage = 'en'
# defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true
# defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    # contentDir = 'content/de'
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Spanish'
    # title = 'Projekt Dokumentation'
    title = 'Portfolio de Suzuka Ka'
    weight = 1
    # [languages.de.params]
      # subtitle = 'Referenz, Tutorials und Erklärungen'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    # title = 'Project Documentation'
    title = "Suzuka Ka's Portfolio"
    weight = 2
    # [languages.en.params]
      # subtitle = 'Reference, Tutorials, and Explanations'

[markup]
  # INFO https://gohugo.io/methods/page/tableofcontents/
  [markup.tableOfContents]
    endLevel = 3
    # ordered = false
    ordered = true
    startLevel = 1

[markup.goldmark.renderer]
unsafe= true
[params]
  galleries_author = 'Suzuka Ka'
  articles_author = 'Suzuka Ka'
  articles_pfp_image = '/images/yo.jpg'
  audios_default_author = 'Suzuka Ka'
  articles_card_type = 2 # options: 1 (simple) or 2 (with more info)
  # is_debug = false # Set to false for relase
  # is_debug = true

  show_galeries_with_same_article_tag = true # If True, when seeing a certain article tag, it will show at the end the galeries that contains that tag you are browsing
  show_featured_articles = true # If True, featured articles will display in the index page
  keywords = ['gamedev', 'gamedeveloper', 'engineer', 'multimedia engineer', '2D art', '3D art', 'music production', 'alicante', 'spain']
  socials = ['github', 'twitter', 'youtube','gumroad', 'itchio', 'email']

