baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'SZK | Suzuka Ka'
theme = 'gallery'
[markup.goldmark.renderer]
unsafe= true
[params]
  [params.socialIcons]
    github = "https://github.com/SuzukaDev"
    youtube = "https://www.youtube.com/@SuzukaKa"
    twitter = "https://x.com/SuzukaKDev"
    gumroad = "https://orb91.gumroad.com/"
    itchio = "https://suzuka.itch.io/"
    email = "mailto:suzukakadev@gmail.com"