baseURL = 'https://example.org/'
# languageCode = 'en-us'
# languageCode = 'es-es'
title = 'SZK | Suzuka Ka'
theme = 'gallery'

# Multilingual
# INFO https://gohugo.io/content-management/multilingual/
defaultContentLanguage = 'en' #NOTE This must match 'default_language'
# defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = true
# defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    # contentDir = 'content/de'
    disabled = false
    languageCode = 'es-ES'
    languageDirection = 'ltr'
    languageName = 'Spanish'
    # title = 'Projekt Dokumentation'
    title = 'Portfolio de Suzuka Ka'
    weight = 1
    # [languages.de.params]
      # subtitle = 'Referenz, Tutorials und Erklärungen'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    # title = 'Project Documentation'
    title = "Suzuka Ka's Portfolio"
    weight = 2
    # [languages.en.params]
      # subtitle = 'Reference, Tutorials, and Explanations'

[markup]
  # INFO https://gohugo.io/methods/page/tableofcontents/
  [markup.tableOfContents]
    endLevel = 3
    # ordered = false
    ordered = true
    startLevel = 1

[markup.goldmark.renderer]
unsafe= true
[params]
  # REFACTOR delete default_language
  # default_language = 'en' # NOTE this must match 'defaultContentLanguage'
  articles_author = 'Suzuka Ka'
  is_debug = false # Set to false for relase
  # is_debug = true
  keywords = ['gamedev', 'gamedeveloper', 'engineer', 'multimedia engineer', '2D art', '3D art', 'music production', 'alicante', 'spain']
  socials = ['github', 'twitter', 'youtube','gumroad', 'itchio', 'email']

